# Generated by Django 2.2.6 on 2019-10-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_myreadingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreadingrecord',
            name='note',
            field=models.TextField(),
        ),
    ]
