# Generated by Django 2.2.6 on 2019-10-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191031_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myreadingrecord',
            old_name='content',
            new_name='note',
        ),
    ]
