# Generated by Django 2.2.6 on 2019-10-31 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191031_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreadingrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
