# Generated by Django 2.2.6 on 2019-10-31 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_myreadingrecord_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myreadingrecord',
            old_name='created_at',
            new_name='created_note_at',
        ),
    ]
