# Generated by Django 2.2.6 on 2019-11-07 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_myreadingrecord_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api', to=settings.AUTH_USER_MODEL),
        ),
    ]
